<footer>
        <div class="container">
            <div class="content about">
                <h2>About Us</h2>
                <br>
                <p> This page was created and assembled by team members of Group 7 - KAAT<br>
                </p>
                <ul class="social-icon">
                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                    <li><a href=""><i class="fa fa-twitter"></i></a></li>
                    <li><a href=""><i class="fa fa-instagram"></i></a></li>
                    <li><a href="https://youtu.be/z3rtm4eAyvg"><i class="fa fa-youtube"></i></a></li>
                </ul>
            </div>
            <div class="content links">
                <h2>Links</h2>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Policies</a></li>
                </ul>
            </div>
            <div class="content contact">
                <h2>Contact</h2>
                <ul class="info">
                    <li>
                        <span><i class="fa fa-map-marker"></i></span>
                        <span>80 Duy Tan<br />
                            Dich Vong Hau, Cau Giay, Hanoi<br />
                            Vietnam</span>
                    </li>
                    <li>
                        <span><i class="fa fa-phone"></i></span>
                        <p><a href="#">+84 123 456 789</a>
                            <br />
                            <a href="#">+84 987 654 321</a>
                        </p>
                    </li>
                    <li>
                        <span><i class="fa fa-envelope"></i></span>
                        <p><a href="#">email@gmail.com</a></p>
                    </li>
                </ul>
                <br>
            </div>
            <div class="map">
                <a href="https://goo.gl/maps/RWShuYAest7bxrc49" target="_blank">
                    <img src="./styles/images/map.png">
                </a>
            </div>
        </div>
        <p class="copyright">© Created by Tri Trung Ton - G7</p>
    </footer>