
<header>
        <div id="menu-bar" class="fa fa-bars"></div>
        <a href="./index.php" class="logo">
            <img src="./styles/images/logo/logo3.png" alt="">
        </a>
        <nav class="navbar">
            <a href="./index.php">Home</a>
            <a href="./product.php" >Product</a>
            <a href="./about.php">About Us</a>
            <a href="./manager.php">Manager</a>
            <a href="./payment.php" >Payment</a>
            <a href="./enhancement.php" >Enhancement</a>
            <a href="https://youtu.be/eSfWCq7hPr4 ">Video</a>
        </nav>
        <div class="icons">
            <a href="test.php"><i class="fa fa-shopping-cart"></i></a>
            <a href=""><i class="fa fa-user"></i></a>
        </div>
</header>